### ISSUE TITLE
0.16 support

### ISSUE THREAD

**Issue by EricReiche** [credomane/FactorioMods_FactorioMaps#17]
Hi,

any chance to get this working with the current version? :)

**Comment by credomane** [comment]
Sorry. Was out of town last week and this week nothing but PC issues. Just got my PC back up and running but probably won't have time until this weekend. :(

It is certainly on my to do list which grew quite a bit this past two weeks.

**Comment by EricReiche** [comment]
awesome! Thanks for your work :)

**Comment by credomane** [comment]
Got a 0.16 release uploaded earlier today.
