### ISSUE TITLE
"FILE_NOT_FOUND" Error in all browsers

### ISSUE THREAD

**Issue by PiggyWhiskey** [credomane/FactorioMods_FactorioMaps#4]
Using Factorio 0.14.19
Mod version 0.7.2

Settings:
Day,
Show Entity
Folder Name : "BobsMods"
Size: -1024x-1024 to 1024x1024
jpeg
Medium grid size.

Generated 5461 images for 256 MB.

Opening in any browser and works fine, but the moment I drag or zoom, it crashes with "FILE_NOT_FOUND"

Testing in Chrome,Firefox,Internet Explorer,Edge.

Any advice?

**Comment by PiggyWhiskey** [comment]
Discovered the issue.

The local URL was "E:\Program Files\steam\steamapps\common\factorio\script-output\FactorioMaps\BobsMods\"

The space in Program Files is causing the problem.

Running directly from "E:\BobsMods" works perfectly.

**Comment by RossBarnie** [comment]
Came across this too. For whatever reason when you zoom or move, the URL changes any spaces to %2520 rather than %20, so the file couldn't be found as it's not looking in the correct directory.

**Comment by credomane** [comment]
Sorry for the long wait. Life had me torn away from Factorio for the past 6ish months. I'm sorta/mostly back!

Most of the index.html code is left overs from the original author of this mod. The mod isn't generating or getting the URI from the user but is updating the already valid one thereby rendering the use of encodeURI moot. I don't know why encodeURI would be needed at all. I'll fix this up plus the other issues inside the index.html generating code and give the whole generateIndex.lua a good once over sometime this week.
