### ISSUE TITLE
Is there any command to run this mod from RCON?

### ISSUE THREAD

**Issue by bonny1992** [credomane/FactorioMods_FactorioMaps#6]
Since it's on a headless server, I'd like to run it from rcon or manually, but I can't find any documentation for this.

**Comment by credomane** [comment]
The taking screenshots doesn't work on headless servers since the server never does anything with graphics. The current Factorio API doesn't provide a way I could load up the graphics manually and render the screenshots myself much like DynMap does in minecraft.

**Comment by bonny1992** [comment]
So I have to download the save, do the map and then restart playing on the server?

Because if I click on the design map the server sees me hanging and then it kicks me out of the server before I finish the project.

**Comment by credomane** [comment]
You should be able to join the server, save the map locally and then load that saved game up in single player to take the screenshots needed for the map. 

I would like to warn/forbid the mod from working in multiplayer but the factorio API is specifically designed to prevent you from knowing if the game is in single-player or multi-player mode when only one player is currently playing. :/

**Comment by bonny1992** [comment]
Maybe a simple warning on mod's page will do the work.
