### ISSUE TITLE
Feature request: Add a extra zoom level, allowing a more detailed view of the map.

### ISSUE THREAD

**Issue by Cerbrus** [credomane/FactorioMods_FactorioMaps#7]
I'd like to be able to zoom in on the map a bit further. (Up to zoom level 9, instead of just 8)

I realize this will roughly quadruple render time / output folder file size. Maybe the last zoom level could be optional with a warning like that...

**Comment by justin-gerhardt** [comment]
It too would find this feature useful

**Comment by Cerbrus** [comment]
A quick-and-dirty change:

On generateMap.lua:

On line 67, replace:  
`for z = minZoomLevel, maxZoomLevel + 1, 1 do  -- max and min zoomlevels`  
With:  
`for z = minZoomLevel, maxZoomLevel + 1, 1 do  -- max and min zoomlevels`  

Then, on the output `index.html`,

On line 21, replace:  
`CustomMapType.prototype.maxZoom = 8;`
With:  
`CustomMapType.prototype.maxZoom = 9;`

Before this change, the rendered map for my save was about 7GB.  
After, it's 32GB. But so much more detail on zoom level 9 ^_^

**Comment by Zappes** [comment]
I wholeheartedly second the feature request. It would be great to have a setting for the maximum zoom level in the UI.
